export enum HeaderEnum {
  issueDate = 'keltDatum',
  completionDate = 'teljesitesDatum',
  paymentDueDate = 'fizetesiHataridoDatum',
  paymentMethod = 'fizmod',
  currency = 'penznem',
  language = 'szamlaNyelve',
  comment = 'megjegyzes',
  exchange = 'arfolyam',
  exchangeBank = 'arfolyamBank',
  orderNumber = 'rendelesSzam',
  proformaInvoiceNumber = 'dijbekeroSzamlaszam',
  depositInvoice = 'elolegszamla',
  finalInvoice = 'vegszamla',
  correctionInvoice = 'helyesbitoszamla',
  correctedInvoiceNumber = 'helyesbitettSzamlaszam',
  proformaInvoice = 'dijbekero',
  invoiceNumberPrefix = 'szamlaszamElotag',
  paid = 'fizetve',
  type = 'tipus',
  invoiceNumber = 'szamlaszam',
}
