export enum VatEnum {
  TAM = 'TAM',
  AAM = 'AAM',
  EU = 'EU',
  EUK = 'EUK',
  MAA = 'MAA',
  ÁKK = 'ÁKK',
  TEHK = 'TEHK',
  HO = 'HO',
  KBAET = 'KBAET',
  TAHK = 'TAHK',
  FAFA = 'F.AFA',
  KAFA = 'K.AFA',
  EUE = 'EUE',
  EUFADE = 'EUFADÉ',
  EUFAD37 = 'EUFAD37',
  ATK = 'ATK',
  NAM = 'NAM',
  EAM = 'EAM',
  KBAUK = 'KBAUK',
}
